server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: rider
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**, 
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path=/clientOrders/**, 
        - id: shop
          uri: http://localhost:8084
          predicates:
            - Path=/shopOrders/**, 
        - id: BoundedContext1659.375
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rider
          uri: http://rider:8080
          predicates:
            - Path=/deliveries/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/clientOrders/**, 
        - id: shop
          uri: http://shop:8080
          predicates:
            - Path=/shopOrders/**, 
        - id: BoundedContext1659.375
          uri: http://boundedContext1659_375:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
