server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: BoundedContext185
          uri: http://localhost:8082
          predicates:
            - Path=/clientOrders/**, 
        - id: BoundedContext46
          uri: http://localhost:8083
          predicates:
            - Path=/shopOrders/**, 
        - id: BoundedContext1499
          uri: http://localhost:8084
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: BoundedContext185
          uri: http://boundedContext185:8080
          predicates:
            - Path=/clientOrders/**, 
        - id: BoundedContext46
          uri: http://boundedContext46:8080
          predicates:
            - Path=/shopOrders/**, 
        - id: BoundedContext1499
          uri: http://boundedContext1499:8080
          predicates:
            - Path=/deliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
